// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlUg1PUJ8_IeCUUjQF3wnEn98e3XDAC8c',
    appId: '1:552097846593:web:f3696006411c205df47dc0',
    messagingSenderId: '552097846593',
    projectId: 'notesapptasya',
    authDomain: 'notesapptasya.firebaseapp.com',
    storageBucket: 'notesapptasya.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAyuBeSAQ0JBnwwzloRzPlY1Fv4DdpU7g',
    appId: '1:552097846593:android:2fa5730106985260f47dc0',
    messagingSenderId: '552097846593',
    projectId: 'notesapptasya',
    storageBucket: 'notesapptasya.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlUg1PUJ8_IeCUUjQF3wnEn98e3XDAC8c',
    appId: '1:552097846593:web:1386531bc543ba76f47dc0',
    messagingSenderId: '552097846593',
    projectId: 'notesapptasya',
    authDomain: 'notesapptasya.firebaseapp.com',
    storageBucket: 'notesapptasya.appspot.com',
  );

}